# -*- coding: utf-8 -*-
"""Exercício módulo 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3sZ4i8g3A6OIVI91jQpRVEWFQ2hk0_Q
"""

# Inserir números para a calculadora

num1 = input("Digite o primeiro número: ")
print('Primeiro número:', num1)
num2 = input("Digite o segundo número: ")
while num2 == '0':
  num2 = input("Zero não é aceito, digite um número válido: ")
else:
  print('Segundo número:', num2)

# Converte os valores recebidos em int e confirma a conversão

num1_convert = int(num1)
print(type(num1_convert))
num2_convert =int(num2)
print(type(num2_convert))

# Pergunta qual operação o usuário quer e traz o resultado, recomeça a operação se for usado um caracter inválido

result= input('Digite a operação desejada: + para soma, - para subtração, * para multiplicação, / para divisão, % para resto da divisão: ')
if result == '+':
  soma = num1_convert + num2_convert
  print("A soma dos elementos é", soma)
elif result == '-':
  subt = num1_convert - num2_convert
  print('A subtração dos elementos é',subt)
elif result == "*":
  mult= num1_convert * num2_convert
  print('A multiplicação dos elementos é', mult)
elif result == "/":
  divi = num1_convert / num2_convert
  print("A divisão dos elementos é", divi)
elif result == "%":
  restdiv = num1_convert % num2_convert
  print("O resto da divisão dos elementos é", restdiv)

#Pergunta se deseja realizar nova operação e realiza se sim

oper2= input('Deseja realizar uma nova operação? (s / n) ')
while oper2 == 's':
  if oper2 == 's':
    num1 = input("Digite o primeiro número: ")
    num2 = input("Digite o segundo número: ")
    while num2 == '0':
      num2 = input("Zero não é aceito, digite um número válido: ")
    num1_convert = int(num1)
    num2_convert = int(num2)
    soma = num1_convert + num2_convert
    subt = num1_convert - num2_convert
    mult= num1_convert * num2_convert
    divi = num1_convert / num2_convert
    restdiv = num1_convert % num2_convert
    result= input('Digite a operação desejada: + para soma, - para subtração, * para multiplicação, / para divisão, % para resto da divisão: ')
    if result == '+':
      print("A soma dos elementos é", soma)
      oper2= input('Deseja realizar uma nova operação? (s / n) ')
    elif result == '-':
      print('A subtração dos elementos é',subt)
      oper2= input('Deseja realizar uma nova operação? (s / n) ')
    elif result == "*":
      print('A multiplicação dos elementos é', mult)
      oper2= input('Deseja realizar uma nova operação? (s / n) ')
    elif result == "/":
      print("A divisão dos elementos é", divi)
      oper2= input('Deseja realizar uma nova operação? (s / n) ')
    elif result == "%":
      print("O resto da divisão dos elementos é", restdiv)
      oper2= input('Deseja realizar uma nova operação? (s / n) ')
else:
  print('Até a próxima!')